# Generated by Django 4.2.2 on 2023-06-13 13:28

from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="district",
            name="province",
        ),
        migrations.RemoveField(
            model_name="village",
            name="district",
        ),
        migrations.AlterModelOptions(
            name="notary",
            options={"verbose_name": "Нотариус", "verbose_name_plural": "Нотариусы"},
        ),
        migrations.AlterModelOptions(
            name="page",
            options={"verbose_name": "Страница", "verbose_name_plural": "Страницы"},
        ),
        migrations.AlterModelOptions(
            name="pagecontent",
            options={"ordering": ["page", "order"], "verbose_name": "Контент страницы"},
        ),
        migrations.AlterModelOptions(
            name="rate",
            options={"verbose_name": "Рейтинг", "verbose_name_plural": "Рейтинги"},
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="body",
            field=models.BooleanField(default=False, verbose_name="Тело"),
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="class_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Названия класса для фронта",
            ),
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="order",
            field=models.SmallIntegerField(default=1, verbose_name="Порядковый номер"),
        ),
        migrations.AlterField(
            model_name="notary",
            name="address",
            field=models.CharField(max_length=100, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="pagecontent",
            name="content",
            field=django_summernote.fields.SummernoteTextField(verbose_name="Контент"),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="District",
        ),
        migrations.DeleteModel(
            name="Province",
        ),
        migrations.DeleteModel(
            name="Village",
        ),
    ]
