# Generated by Django 4.2.2 on 2023-07-02 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_klass_subject_alter_pagecontent_options_lesson"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="klass",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="teacher",
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="style",
            field=models.TextField(blank=True, null=True, verbose_name="CSS Стиль"),
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Klass",
        ),
        migrations.DeleteModel(
            name="Lesson",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
    ]
